name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: server/node_modules
          key: ${{ runner.OS }}-yarn-cache-server-${{ hashFiles('**/server/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-server-
      - name: Build server code
        run: |
          cd server
          yarn --frozen-lockfile
          yarn build
          yarn export-types
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  publish-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-yarn-cache-client-${{ hashFiles('**/client/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-client-
      - name: Build client code
        run: |
          cd client
          yarn --frozen-lockfile
          yarn build
          yarn export-types
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
